class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mir1'
        self.UnzipMirrorCommand = 'unzipm1'
        self.TarMirrorCommand = 'tarm1'
        self.CancelMirror = 'cancl1'
        self.CancelAllCommand = 'canclall1'
        self.ListCommand = 'list1'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users1'
        self.AuthorizeCommand = 'auth1'
        self.UnAuthorizeCommand = 'unauth1'
        self.AddSudoCommand = 'addsudo1'
        self.RmSudoCommand = 'rmsudo1'
        self.PingCommand = 'ping'
        self.RestartCommand = 'release1'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help1'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'stest1'
        self.CloneCommand = 'copy1'
        self.CountCommand = 'count1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.UsageCommand = 'usage1'
        self.MediaInfoCommand = 'mediainfo1'
        self.ConfigMenuCommand = 'config1'
        self.ShellCommand = 'shell1'
        self.UpdateCommand = 'uprelease1'

BotCommands = _BotCommands()
